services:
  wordhelper-dev:
    image: nexus.jbrmmg.me.uk:8084/wordhelper-dev:latest
    container_name: wordhelper-dev
    restart: unless-stopped
    volumes:
      - /var/lib/wordhelper:/var/lib/wordhelper
    networks:
      jbr-network:
        aliases:
          - wordhelper

  wordclue-dev:
    image: nexus.jbrmmg.me.uk:8084/wordclue-dev:latest
    container_name: wordclue-dev
    restart: unless-stopped
    volumes:
      - /var/lib/wordhelper:/var/lib/wordhelper
    networks:
      jbr-network:
        aliases:
          - wordclue

networks:
  jbr-network:
    external: true
