services:
  wordhelper:
    image: nexus.jbrmmg.me.uk:8084/wordhelper:latest
    container_name: wordhelper
    restart: unless-stopped
    ports:
      - "5000:8080"
    networks:
      - jbr-network

  wordclue:
    image: nexus.jbrmmg.me.uk:8084/wordclue:latest
    container_name: wordclue
    restart: unless-stopped
    ports:
      - "5001:8080"
    networks:
      - jbr-network

networks:
  jbr-network:
    external: true
