services:
  wordhelper:
    image: nexus.jbrmmg.me.uk:8084/wordhelper:latest
    container_name: wordhelper
    restart: unless-stopped
    volumes:
      - /var/lib/wordhelper:/var/lib/wordhelper
    networks:
      - jbr-network

  wordclue:
    image: nexus.jbrmmg.me.uk:8084/wordclue:latest
    container_name: wordclue
    restart: unless-stopped
    volumes:
      - /var/lib/wordhelper:/var/lib/wordhelper
    networks:
      - jbr-network

  connections:
    image: nexus.jbrmmg.me.uk:8084/connections:latest
    container_name: connections
    restart: unless-stopped
    networks:
      - jbr-network

networks:
  jbr-network:
    external: true
