name: Development Build

on:
  push:
    branches-ignore:
      - Release

jobs:
  build:
    runs-on: wordhelper-dev

    steps:
      - uses: actions/checkout@v4

      - name: Compute version
        run: echo "VERSION=$(date +'%Y.%m.%d')-SNAPSHOT" >> $GITHUB_ENV

      - name: Build wordhelper Docker image
        run: |
          docker build \
            -f docker/Dockerfile-scanner \
            -t nexus.jbrmmg.me.uk:8083/wordhelper-dev:${{ github.sha }} \
            -t nexus.jbrmmg.me.uk:8083/wordhelper-dev:latest \
            .

      - name: Build wordclue Docker image
        run: |
          docker build \
            -f docker/Dockerfile-clue \
            -t nexus.jbrmmg.me.uk:8083/wordclue-dev:${{ github.sha }} \
            -t nexus.jbrmmg.me.uk:8083/wordclue-dev:latest \
            .

      - name: Build connections Docker image
        run: |
          docker build \
            -f docker/Dockerfile-connections \
            -t nexus.jbrmmg.me.uk:8083/connections-dev:${{ github.sha }} \
            -t nexus.jbrmmg.me.uk:8083/connections-dev:latest \
            .

      - name: Build codeword Docker image
        run: |
          docker build \
            -f docker/Dockerfile-codeword \
            -t nexus.jbrmmg.me.uk:8083/codeword-dev:${{ github.sha }} \
            -t nexus.jbrmmg.me.uk:8083/codeword-dev:latest \
            .

      - name: Push to Nexus Docker registry
        run: |
          docker login nexus.jbrmmg.me.uk:8083 \
            -u deployment \
            -p ${{ secrets.NEXUS_PASSWORD }}
          docker push nexus.jbrmmg.me.uk:8083/wordhelper-dev:${{ github.sha }}
          docker push nexus.jbrmmg.me.uk:8083/wordhelper-dev:latest
          docker push nexus.jbrmmg.me.uk:8083/wordclue-dev:${{ github.sha }}
          docker push nexus.jbrmmg.me.uk:8083/wordclue-dev:latest
          docker push nexus.jbrmmg.me.uk:8083/connections-dev:${{ github.sha }}
          docker push nexus.jbrmmg.me.uk:8083/connections-dev:latest
          docker push nexus.jbrmmg.me.uk:8083/codeword-dev:${{ github.sha }}
          docker push nexus.jbrmmg.me.uk:8083/codeword-dev:latest

      - name: Deploy
        run: |
          docker login nexus.jbrmmg.me.uk:8084 \
            -u deployment \
            -p ${{ secrets.NEXUS_PASSWORD }}
          docker compose -f docker-compose-dev.yml pull
          docker compose -f docker-compose-dev.yml up -d
